### =======================================
### ZONA DE MENSAJERÍA ENTRE PCs
### =======================================

### POST - Enviar un mensaje a la otra PC
POST http://localhost:5000/api/mensajes/enviar
Content-Type: application/json

{
  "ip_destino": "192.168.10.39", 
  "mensaje": "¡Hola! Probando el chat bidireccional desde mi PC."
}