@baseUrl = http://localhost:5000/api

### POST - Enviar un mensaje a la otra PC
POST {{baseUrl}}/mensajes/enviar
Content-Type: application/json

{
  "ip_destino": "192.168.220.100", 
  "mensaje": "¡Hola! Este es un mensaje directo sin base de datos."
}